### ISSUE TITLE
Menu navigation changes from number to bullet point

### ISSUE THREAD

**Issue by cynthiaftw** [carpentries/workbench#42]
When I click on the menu let's say number 2 in a list. It changes to a bullet point so you don't know where you are. It should stay as a number 2. At first I thought it took me to a level down and took forever long for me to figure out it was not moving between levels just changing the number to a bullet. It is the worst and makes you loose yourself in the navigation. It is confusing to new users as well. You have a hard time directing people to the links - now I hoover and point out the change and have to click several times back and forth for people to follow in a lesson.

**Comment by zkamvar** [comment]
Thank you for opening this issue @cynthiaftw. From your description, this is definitely something that hinders accessibility (specifically I think it most pertinantly falls into the realm of the need for [consistent navigation](https://www.w3.org/WAI/WCAG21/Understanding/consistent-navigation.html) and should be fixed. At the moment, the side bar looks like this:

![a screenshot of a sidebar with 8 numbered sections. The third section is bold with a bullet point and a secondary list of sections below it, but it has no number](https://user-images.githubusercontent.com/3639446/228854356-2680ddd7-7979-4891-bc1f-f63575bb6afb.png)

Do you think adding the episode number would be a good solution to the problem you describe? The bullet point is there as an indicator that the it's the active section. 

![the same sidebar as above, but the third section has the number 3. appended before the text](https://user-images.githubusercontent.com/3639446/228854154-98e8bd30-6fc1-4692-af03-95e905dd15e6.png)

**Comment by cynthiaftw** [comment]
This would be perfect, you could see that you are still where you thought you were going. Could also state to the class when directing people click on 3 and they would still see that is where they landed. I do think this is a great solution. Also I like that the bullet is there to indicate that is what you are reading.

Cynthia Henry
College of Human Sciences
Texas Tech University
(806) 834-0898
***@***.******@***.***>
http://guides.library.ttu.edu/hs
Make an Appointment<https://cal.library.ttu.edu/appointments/libcal?u=48731>

**Comment by zkamvar** [comment]
Hello, I've fixed this in https://github.com/carpentries/sandpaper/pull/472 and the new version of {sandpaper} will be available to all the lessons in about an hour. The lessons will all rebuild around 00:00 UTC on Tuesday. If you see no change after that, feel free to reopen the issue.
